### ISSUE TITLE
Banksim error with IMRPhenomXPHM and NRSur7dq4 waveforms

### ISSUE THREAD

**Issue by MariaAssiduo** [gwastro/sbank#30]
I succesfully obtained two template banks with the family waveforms IMRPhenomXPHM and NRSur7dq4 using SBank. Now I am trying to calculate the effectualness of these banks using Banksim through the following tests:
A (B). choosing the IMRPhenomXPHM as bank-seed (template-approximant) and the NRSur7dq4 as injections (signal-approximant) and viceversa;

I get the following errors:
(A) pycbc_banksim: error: argument --template-approximant: invalid choice: 'IMRPhenomXPHM' (choose from 'EOBNRv2'....)
(B) pycbc_banksim: error: argument --signal-approximant: invalid choice: 'IMRPhenomXPHM' (choose from 'EOBNRv2'....)

It seems that the waveforms IMRPhenomXPHM are not implemented in Banksim? How can I add them?

Thanks in advance.

**Comment by MariaAssiduo** [comment]
I searched in site-packages pycbc.waveform and looked the scripts bank.py and waveform.py but I cannot find the list of the templates approximant.

**Comment by spxiwh** [comment]
@MariaAssiduo It looks like you are using `pycbc_banksim` (which I would recommend as its good to have a banksim that is not tied to the bank generator .... If there's an issue in sbank, it will likely be present in sbank's banksim as well). I guess this makes this a PyCBC issue rather than an sbank issue.

If you are getting "invalid choice" for IMRPhenomXPHM then the version of lalsuite you are using with PyCBC is likely an old one (I think `pycbc_inspiral --version` will print off information about the lalsuite versions PyCBC is calling).

This then leads to a few questions:

* Are you using python2? If so then `pip install lalsuite` will install an old version of lalsuite from before python3 support was removed. You can install a newer version of lalsuite from source and link that from a python2 PyCBC install, but I think the latest version of lalsuite now does not support python3 at all.
* If using python3 then `pip install --upgrade lalsuite` (or the conda equivalent if using conda) should get what you want. We are currently in the process of abandoning python2 but there is a possibility of hitting some issues with python2<->python3 conversion in the meantime (we are having a PyCBC meeting later this week, where one of the things we will try and resolve is any lingering python2<->python3 transition issues https://github.com/gwastro/pycbc/wiki/PyCBC-Remote-Meeting-16-17-September-2021).

**Comment by spxiwh** [comment]
PyCBC does not have an explicit list of waveforms as sbank does. It just asks lalsimulation directly what is available (sbank does not do this as it needs to identify whether waveforms have higher-order modes/precession).

That's also important: If you want to use the higher-order mode statistic for the templates you would need to use this PyCBC banksim executable https://github.com/gwastro/pycbc/blob/master/bin/pycbc_banksim_skymax with the option `--sky-maximization-method hom`.
